import type { ProjectMetadata } from "@/lib/project-types";

const spacesBySlug: Record<string, string[]> = {
  "tkg-taekwang-gimhae": ["공용홀", "오피스", "회의실", "임원실", "VIP 식당", "피트니스룸"],
  "lg-chem-yongseong-cafeteria": ["공용홀", "식당 홀", "화장실"],
  "lg-chem-daesan-residence": ["헬스장", "탈의실", "사우나", "화장실", "창고", "PLAY ZONE", "GAME ZONE", "CAFETERIA", "스크린야구장"],
  "lx-international-office": ["대회의실", "사무실", "인터뷰룸", "포커스룸", "임원실", "회의실", "고충처리실"],
  "beomyang-reus-cheongnyangni": ["공용홀", "세대"],
  "lx-holdings-office": ["VIP 집무실", "VIP 화장실", "응접실", "대회의실", "임원실", "회의실", "사무공간", "OA", "탕비"],
  "urbanus-office": ["사무실", "임원실", "회의실", "로비"],
  "the-first-ocean-view-busan": ["공용홀", "세대"],
  "richeville-s-geomdan": ["공용홀", "세대"],
  "gwell-estate-jangwi": ["공용홀", "세대"],
  "lg-chem-yeosu-y2c": ["로비", "엘리베이터 홀", "대회의실", "브리핑실", "화장실", "언택트룸"],
  "lg-hh-cheongju": ["로비", "쇼룸", "VIP룸", "VIP 화장실", "회의실"],
  "jungheung-school-library": ["복도", "라운지", "영상학습실", "도서관", "다목적실", "위클래스"],
  "lg-science-park-isc": ["업무공간", "카페테리아", "아이디어룸"],
  "prugio-city-sinjungdong": ["공용홀", "세대"],
  "lg-science-park-dp3": ["로비", "고객 접견실", "로비 아트리움", "컨퍼런스룸", "휴게실", "화상회의실", "엘리베이터 홀", "정보자료실", "업무공간"],
  "lg-hausys-design-center": ["디자인 라이브러리"],
  "hillstate-songjeong": ["공용홀", "세대"],
  "the-first-wellga-jinju": ["공용홀", "세대"],
  "la-terrasse-cheongdam": ["공용홀", "세대"],
  "taekwang-office": ["로비", "사무실", "라운지"],
  "hillstate-ilsan-kintex": ["공용홀", "세대"],
  "hillstate-eco-magoknaru": ["공용홀", "세대"],
  "ramada-encore-magok": ["공용홀", "객실"],
  "lge-incheon-daycare": ["교실", "유희실", "화장실", "복도"],
  "g-prime-tower-ulsan": ["공용홀", "세대"],
  "sk-hynix-office": ["회의실", "사무실", "직원 복지시설", "임원실"],
  "lg-chem-cheongju-welfare": ["복지공간", "사내식당"],
  "cubi-maison-de-terrace-changwon": ["공용홀", "세대"],
  "lg-cns-ceo-zone": ["집무실", "접견실", "회의실", "로비"],
  "lg-uplus-asan": ["구내식당", "강의실", "휴게실"],
  "bw-wedding-hall": ["외관", "홀 대기실", "식당"],
  "doksan-residence": [],
  "hermoso-yongsan": ["공용홀", "세대"],
  "yongil-bojeong-residence": [],
  "woojin-godeok-office": [],
  "ilsan-ipark-model-house": ["공용홀", "세대"],
  "paju-model-house": ["홍보관", "세대"],
  "pocheon-soheul-house": [],
  "pocheon-idong-house": [],
};

type ProjectRecord = Omit<ProjectMetadata, "spaces" | "coverIndex">;

const records: ProjectRecord[] = [
  { slug: "tkg-taekwang-gimhae", sourceFolder: "TKG 태광 김해공장", title: "TKG 태광 김해공장", completedAt: "2023-10", type: "commercial", category: "corporate", location: "경남 김해시", featuredOrder: 1 },
  { slug: "lg-chem-yongseong-cafeteria", sourceFolder: "LGC 용성관 식당", title: "LG화학 여수 용성관 식당", completedAt: "2022-07", type: "commercial", category: "corporate", location: "전남 여수시", featuredOrder: 2 },
  { slug: "lg-chem-daesan-residence", sourceFolder: "2022.03_LGC 대산사택", title: "LG화학 대산사택", completedAt: "2022-03", type: "commercial", category: "corporate", location: "충남 서산시", featuredOrder: 3 },
  { slug: "lx-international-office", sourceFolder: "2021.12_LX 인터내셔널", title: "LX 인터내셔널 오피스", completedAt: "2021-12", type: "commercial", category: "corporate", location: "서울시 종로구", featuredOrder: 4 },
  { slug: "beomyang-reus-cheongnyangni", sourceFolder: "2021.11_범양레우스 청량리 모델하우스", title: "청량리 범양레우스 씨엘로네 모델하우스", completedAt: "2021-11", type: "residential", category: "model-house", location: "서울시 동대문구", featuredOrder: 5 },
  { slug: "lx-holdings-office", sourceFolder: "2021.06_LX 홀딩스", title: "LX 홀딩스 오피스", completedAt: "2021-06", type: "commercial", category: "corporate", location: "서울시 종로구", featuredOrder: 6 },
  { slug: "urbanus-office", sourceFolder: "2021.04_어반어스 오피스", title: "어반어스 오피스", completedAt: "2021-04", type: "commercial", category: "corporate", location: "서울시 강남구", featuredOrder: 7 },
  { slug: "the-first-ocean-view-busan", sourceFolder: "2021.03_더 퍼스트 오션뷰 부산 모델하우스", title: "부산 일광역 더 퍼스트 오션뷰 모델하우스", completedAt: "2021-03", type: "residential", category: "model-house", location: "부산시 기장군", featuredOrder: 8 },
  { slug: "richeville-s-geomdan", sourceFolder: "2021.02_법조타운 리슈빌S 검단 모델하우스", title: "검단역 법조타운 리슈빌S 모델하우스", completedAt: "2021-02", type: "residential", category: "model-house", location: "인천시" },
  { slug: "gwell-estate-jangwi", sourceFolder: "2020.11_지웰 에스테이트 장위 모델하우스", title: "장위 지웰 에스테이트 모델하우스", completedAt: "2020-11", type: "residential", category: "model-house", location: "서울시 성북구" },
  { slug: "lg-chem-yeosu-y2c", sourceFolder: "2020.12_LGC 여수 Y2C 복합동 신축공사", title: "LG화학 여수 Y2C 복합동", completedAt: "2020-12", type: "commercial", category: "corporate", location: "전남 여수시" },
  { slug: "lg-hh-cheongju", sourceFolder: "2020.08_LG생활건강 청주", title: "LG생활건강 청주 T/P 프로젝트", completedAt: "2020-08", type: "commercial", category: "corporate", location: "충북 청주시" },
  { slug: "jungheung-school-library", sourceFolder: "2020.01_중흥초등학교 도서관", title: "중흥초등학교 도서관", completedAt: "2020-01", type: "commercial", category: "education", location: "경기 부천시" },
  { slug: "lg-science-park-isc", sourceFolder: "2019.04_LG사이언스 파크 마곡", title: "LG사이언스파크 마곡 ISC동", completedAt: "2019-04", type: "commercial", category: "corporate", location: "서울시 강서구" },
  { slug: "prugio-city-sinjungdong", sourceFolder: "2019.02_푸르지오시티 신중동 모델하우스", title: "신중동역 랜드마크 푸르지오시티 모델하우스", completedAt: "2019-02", type: "residential", category: "model-house", location: "경기 부천시" },
  { slug: "lg-science-park-dp3", sourceFolder: "2018.01_LG사이언스 파크 마곡 DP3", title: "LG사이언스파크 마곡 DP3", completedAt: "2018-01", type: "commercial", category: "corporate", location: "서울시 강서구" },
  { slug: "lg-hausys-design-center", sourceFolder: "2018.01_LG 하우시스 마곡 디자인 센터", title: "LG하우시스 마곡 디자인센터", completedAt: "2018-01", type: "commercial", category: "corporate", location: "서울시 강서구" },
  { slug: "hillstate-songjeong", sourceFolder: "2018.01_힐스테이트 송정 모델하우스", title: "힐스테이트 송정 모델하우스", completedAt: "2018-01", type: "residential", category: "model-house", location: "경북 구미시" },
  { slug: "the-first-wellga-jinju", sourceFolder: "2017.08_더 퍼스트 웰가시티 신진주 모델하우스", title: "신진주역세권 더 퍼스트 웰가시티 모델하우스", completedAt: "2017-08", type: "residential", category: "model-house", location: "경남 진주시" },
  { slug: "la-terrasse-cheongdam", sourceFolder: "2017.04_라테라스 청담 모델하우스", title: "라테라스 청담 모델하우스", completedAt: "2017-04", type: "residential", category: "model-house", location: "서울시 강남구" },
  { slug: "taekwang-office", sourceFolder: "2016.12_태광실업 오피스동 신축", title: "태광실업 오피스동", completedAt: "2016-12", type: "commercial", category: "corporate", location: "경남 김해시" },
  { slug: "hillstate-ilsan-kintex", sourceFolder: "2016.07_힐스테이트 일산 킨텍스 모델하우스", title: "일산 힐스테이트 킨텍스 레이크뷰 모델하우스", completedAt: "2016-07", type: "residential", category: "model-house", location: "경기 고양시" },
  { slug: "hillstate-eco-magoknaru", sourceFolder: "2016.06_힐스테이트 에코 마곡나루 모델하우스", title: "힐스테이트 에코 마곡나루 모델하우스", completedAt: "2016-06", type: "residential", category: "model-house", location: "서울시 강서구" },
  { slug: "ramada-encore-magok", sourceFolder: "2016.06_라마다 앙코르 호텔 마곡 모델하우스", title: "라마다 앙코르 서울 마곡호텔 모델하우스", completedAt: "2016-06", type: "residential", category: "model-house", location: "서울시 강서구" },
  { slug: "lge-incheon-daycare", sourceFolder: "2016.02_LG전자 인천캠퍼스 어린이집", title: "LG전자 인천캠퍼스 어린이집", completedAt: "2016-02", type: "commercial", category: "education", location: "인천시 서구" },
  { slug: "g-prime-tower-ulsan", sourceFolder: "2016.02_G-Prime 타워 울산 모델하우스", title: "울산 G-Prime Tower 모델하우스", completedAt: "2016-02", type: "residential", category: "model-house", location: "울산시" },
  { slug: "sk-hynix-office", sourceFolder: "2015.11_SK 하이닉스 오피스동", title: "SK하이닉스 M14 오피스동", completedAt: "2015-11", type: "commercial", category: "corporate", location: "경기 이천시" },
  { slug: "lg-chem-cheongju-welfare", sourceFolder: "2015.11_LG 화학 청주복지관", title: "LG화학 청주복지관", completedAt: "2015-11", type: "commercial", category: "corporate", location: "충북 청주시" },
  { slug: "cubi-maison-de-terrace-changwon", sourceFolder: "2015.03_큐비 메종드테라스 창원 모델하우스", title: "창원 큐비 메종드테라스", completedAt: "2015-03", type: "residential", category: "model-house", location: "경남 창원시" },
  { slug: "lg-cns-ceo-zone", sourceFolder: "2015.01_LG CNS 임원실", title: "LG CNS 임원실 CEO ZONE", completedAt: "2015-01", type: "commercial", category: "corporate", location: "서울시 영등포구" },
  { slug: "lg-uplus-asan", sourceFolder: "2015.01_LG유플러스 아산지구국", title: "LG유플러스 아산지구국", completedAt: "2015-01", type: "commercial", category: "corporate", location: "충남 아산시" },
  { slug: "bw-wedding-hall", sourceFolder: "BW 웨딩홀", title: "BW 웨딩홀", type: "commercial", category: "retail" },
  { slug: "doksan-residence", sourceFolder: "독산동", title: "독산동 공동주택", type: "residential", category: "residential", location: "서울시 금천구" },
  { slug: "hermoso-yongsan", sourceFolder: "에르모소 용산 모델하우스", title: "에르모소 용산 모델하우스", type: "residential", category: "model-house", location: "서울시 용산구" },
  { slug: "yongil-bojeong-residence", sourceFolder: "용일 보정동", title: "용일 보정동 공동주택", type: "residential", category: "residential", location: "경기 용인시" },
  { slug: "woojin-godeok-office", sourceFolder: "우진산전 고덕 사옥", title: "우진산전 고덕 사옥", type: "commercial", category: "corporate", location: "서울시 강동구" },
  { slug: "ilsan-ipark-model-house", sourceFolder: "일산 아이파크 모델하우스", title: "일산 아이파크 모델하우스", type: "residential", category: "model-house", location: "경기 고양시" },
  { slug: "paju-model-house", sourceFolder: "파주 모델하우스", title: "파주 모델하우스", type: "residential", category: "model-house", location: "경기 파주시" },
  { slug: "pocheon-soheul-house", sourceFolder: "포천 소흘", title: "포천 소흘 단독주택", type: "residential", category: "residential", location: "경기 포천시" },
  { slug: "pocheon-idong-house", sourceFolder: "포천 이동", title: "포천 이동 단독주택", type: "residential", category: "residential", location: "경기 포천시" },
];

export const projectMetadata: ProjectMetadata[] = records.map((record) => ({
  ...record,
  spaces: spacesBySlug[record.slug] ?? [],
  coverIndex: 0,
}));
